backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subtext", name: "subtext", widget: "text" }
