backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
